# Generated by Django 2.2.6 on 2019-11-20 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ourCalendar', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='name',
            field=models.CharField(default='TEST', max_length=200),
        ),
    ]
