# Generated by Django 2.2.6 on 2019-11-20 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ourCalendar', '0002_event_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='CalculatedCalendar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('name', models.CharField(default='TEST', max_length=200)),
            ],
        ),
    ]
