# Generated by Django 2.2.6 on 2019-11-20 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ourCalendar', '0003_calculatedcalendar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calculatedcalendar',
            name='name',
            field=models.CharField(max_length=200),
        ),
    ]
