# Generated by Django 2.2.6 on 2019-11-20 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ourCalendar', '0004_auto_20191120_1401'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CalculatedCalendar',
        ),
    ]
