# Generated by Django 2.2.6 on 2019-11-22 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='empInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=300)),
                ('days', models.CharField(default='11111111', max_length=300)),
                ('mon', models.CharField(default='0000000000000000', max_length=300)),
                ('tues', models.CharField(default='0000000000000000', max_length=300)),
                ('wed', models.CharField(default='0000000000000000', max_length=300)),
                ('thurs', models.CharField(default='0000000000000000', max_length=300)),
                ('fri', models.CharField(default='0000000000000000', max_length=300)),
                ('sat', models.CharField(default='0000000000000000', max_length=300)),
                ('sun', models.CharField(default='0000000000000000', max_length=300)),
            ],
        ),
    ]
