# Generated by Django 2.2.6 on 2019-11-03 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='empinfo',
            name='days',
            field=models.CharField(default='11111111', max_length=300),
        ),
    ]
