# Generated by Django 2.2.6 on 2019-11-03 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_empinfo_days'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empinfo',
            name='Name',
            field=models.CharField(max_length=300),
        ),
    ]
