# Generated by Django 2.2.6 on 2019-12-05 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20191125_2106'),
    ]

    operations = [
        migrations.AddField(
            model_name='empinfo',
            name='Companyname',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AddField(
            model_name='empinfo',
            name='Email',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AddField(
            model_name='empinfo',
            name='Firstname',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AddField(
            model_name='empinfo',
            name='Lastname',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AddField(
            model_name='empinfo',
            name='Password',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AlterField(
            model_name='empinfo',
            name='Name',
            field=models.CharField(default='', max_length=300),
        ),
    ]
