# Generated by Django 2.2.6 on 2019-12-04 23:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20191205_0419'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empinfo',
            name='Companyname',
        ),
        migrations.RemoveField(
            model_name='empinfo',
            name='Email',
        ),
        migrations.RemoveField(
            model_name='empinfo',
            name='Password',
        ),
    ]
