# Generated by Django 2.2.6 on 2019-12-05 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20191204_2359'),
    ]

    operations = [
        migrations.AddField(
            model_name='empinfo',
            name='Email',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AddField(
            model_name='empinfo',
            name='Password',
            field=models.CharField(default='', max_length=300),
        ),
    ]
