# Generated by Django 2.2.6 on 2019-12-05 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20191205_0509'),
    ]

    operations = [
        migrations.AddField(
            model_name='empinfo',
            name='Username',
            field=models.CharField(default='', max_length=300),
        ),
    ]
