# Generated by Django 2.2.6 on 2019-12-05 20:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_currentuser'),
    ]

    operations = [
        migrations.RenameField(
            model_name='currentuser',
            old_name='currentUsename',
            new_name='currentUsername',
        ),
    ]
